version: 2
sources:
  - name: datafeed_shared_schema
    database: "{{('dbt_db')}}"
    schema: staging_layer

    tables:
      - name: STG_CUSTOMERS
      - name: STG_PAYMENTS
      - name: STG_ORDERS
     


