version: 2
sources:
  - name: datafeed_shared_schema
    database: "{{('dbt_db')}}"
    schema: staging_layer

    tables:
      - name: stg_customers
      - name: stg_payments
      - name: stg_orders
      - name: stg_items
      - name: stg_products
      - name: stg_supplies
      - name: stg_stores
